<!-- generated-by: groundrules v1.6.1 -->
# Loop — autonomous maker/verifier execution for {{PROJECT_NAME}}

This directory makes {{PROJECT_NAME}} executable by an **autonomous loop**, not only interactively. It
is opt-in scaffolding generated by groundrules. The loop *writes the code fast*; the rest of the repo
(ADRs, LEARNINGS, the *why*) keeps the **understanding** of it — loops create comprehension debt, the
durable docs are the antidote.

## The contract in one paragraph

The **maker** ([`maker.md`](maker.md)) takes the first ready task from [`backlog.md`](backlog.md),
implements *only* that task, runs its acceptance test, and reports one of **DONE / DONE_WITH_CONCERNS /
BLOCKED / NEEDS_CONTEXT**. The **verifier** ([`verifier.md`](verifier.md)) is a *separate* role that
**does not trust the maker's report**: it re-runs the test, reads the actual diff, checks the
`## Invariants` in `CLAUDE.md`, and reviews in two ordered stages — **(1) spec-compliance** (incl.
"is the test even strong enough?") **THEN (2) code-quality**. On PASS the loop commits and checks the
task off; on `BLOCKED` or a persistent `REJECT`, it writes [`blocked.md`](blocked.md) and escalates to
you (the realization→reflection backward crossing).

## Files

| File | Role |
|------|------|
| `backlog.md` | The loop's task list — **loop-safe tasks only**. The loop reads this, never `PLAN.md`. |
| `maker.md` | The maker prompt. |
| `verifier.md` | The verifier prompt (independent; distrusts the report). |
| `LOOP.md` | The fixed prompt replayed each iteration. |
| `run-loop.sh` | The capped runner (hard `MAX` ceiling — anti-runaway). |
| `blocked.md` | Written by the loop when it parks a decision for you (the backward crossing). |
| `lessons.md` | Optional — lessons the loop accumulates across iterations. |

## Running it

```bash
# from the project root; MAX caps the iterations (anti-runaway, mandatory)
bash loop/run-loop.sh --max 5
```

The runner drives `claude -p` headless, a fresh agent each iteration (the model forgets; the repo
remembers). It stops on an empty backlog or when `MAX` is reached.

## Triaging `blocked.md` (the backward crossing)

When the loop writes `blocked.md`, it has hit something it **can't verify its way out of** and has
re-entered **reflection** — your territory. Triage every open blocker; this is the price of running the
loop. For each, pick **one** route by *why* it blocked:

| Why it blocked | Route | How |
|---|---|---|
| The task was **too big / vague** to be atomic | **Re-decompose** | Split it into atomic, testable sub-tasks — run `/groundrules:realize` again on the smaller pieces. |
| It hid a **real decision** the spec didn't settle | **Decide → ADR** | A **human** makes the call and records it with `/groundrules:add-adr`; then re-add the now-decided task to `loop/backlog.md` (via `realize` or by hand). |
| It needs a **human touch** the loop can't give (exploratory, cross-cutting, judgement) | **Fix interactively** | Do it in a normal session; leave it `[supervised]`. |

**The decision is the human's, not the triager's.** Triage *routes* a blocker; it does **not** resolve a
parked decision by guessing (same guard as the maker — could-act ≠ cleared-to-act). An agent triaging
may re-decompose and fix interactively, but for a hidden decision it routes to an ADR and **waits for the
human** — it never invents the answer.

**If a blocker fits more than one row**, prefer in this order: **Decide → ADR** (a hidden decision must
be settled first) **> Re-decompose > Fix interactively**.

**Closing a blocker** (the audit trail — `blocked.md` is not a graveyard): replace its
`Resolution: (open — awaiting triage)` line, **beginning with the route label** so it stays greppable:
- `Resolution: Re-decompose → <N tasks re-added to backlog.md>`
- `Resolution: Decide → ADR (pending human decision)` — a legitimate *tracked, not closed* state; becomes
  `Decide → ADR 00NN; task re-added` only once the human decides. **Don't fabricate an ADR number for a
  decision not yet made.**
- `Resolution: Fix interactively → <commit / "stays [supervised]">`

**A resolved blocker should leave the repo smarter, not just unblocked** — a decision becomes an ADR
that makes the next run smarter (the loop *bonifies* the repo).

## Boundaries

- **The loop owns `loop/`; you own `PLAN.md`.** Keep loop-safe tasks here, everything else in `PLAN.md`.
- **State your `## Invariants`** in `CLAUDE.md` — the verifier enforces them every iteration.
- Loops fit **atomic, testable, isolatable** work. Exploratory / cross-cutting / decision work stays
  interactive (`[supervised]`).
- **A `[loop]` task needs a pre-written acceptance test that is currently red**, authored separately
  from the maker (writer ≠ maker) — `/groundrules:realize` enforces this. It is the loop's back
  pressure, **not** a global TDD rule: interactive work needs no pre-written test (the human is the
  back pressure).
